### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by algebio** [BodenmillerGroup/imctools#109]
* imctools version: Version 2.1.5
* Python version: 3.7
* Operating System: Windows 10

### Description

I got a long error message when running imc_preprocesing on jupyter notebook after step Generate the analysis stacks

### What I Did

```
%%time
ome2analysis.omefolder_to_analysisfolder(folder_path_ome, folder_path_analysis, panel_csv_file=file_path_csv_panel,
                                         analysis_stacks=(list_analysis_stacks), metalcolumn=csv_panel_metal)

Error in full panel 26mar2021_s0_a1_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in full panel 26mar2021_s0_a1_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in full panel 26mar2021_s0_a2_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in full panel 26mar2021_s0_a2_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in full panel 26mar2021_s0_a3_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in full panel 26mar2021_s0_a3_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in PR2565917_8um_s1_a1_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
Error in PR2565917_8um_s1_a1_ac.ome.tiff
Traceback (most recent call last):
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 159, in omefolder_to_analysisfolder
    omefile_2_analysisfolder(
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 99, in omefile_2_analysisfolder
    metals = get_metals_from_panel(panel_csv_file, usedcolumn, metalcolumn, sort_channels)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 51, in get_metals_from_panel
    metals = sorted(metals, key=mass_from_met)
  File "C:\Users\njo47\Anaconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\ome2analysis.py", line 49, in mass_from_met
    return int("".join([m for m in x if m.isdigit()])), x
ValueError: invalid literal for int() with base 10: ''
```
Sample data [here](https://newcastle-my.sharepoint.com/:f:/g/personal/njo47_newcastle_ac_uk/EqtgC1lTz3dDmtpsHAtdebYBuaGOiBTrq9wycq2wjGRiRw?e=a2ICkq)

Regards
Juan

**Comment by votti** [comment]
Hi Juan,

Sorry for taking so long.

The issue is your .csv file that contains trailing, empty rows
![image](https://user-images.githubusercontent.com/3743016/117715196-3ed30080-b1d8-11eb-9701-d5b7031610d6.png)

If you delete them using a text editor, this should work fine again.

Cheers, Vito
