### ISSUE TITLE
Runtime error: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by zhanxw** [BodenmillerGroup/imctools#64]
Hello,

I installed the imctools using pip and encountered the following error:

> python
Python 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import imctools.io.mcdparser as mcdparser
>>> import imctools.io.txtparser as txtparser
>>> import imctools.io.ometiffparser as omeparser
>>> import imctools.io.mcdxmlparser as meta
>>>
>>> fn_mcd = '20171228_spleen315_500x500.mcd'
>>> mcd = mcdparser.McdParser(fn_mcd)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/io/mcdparser.py", line 31, in __init__
    McdParserBase.__init__(self, filename, filehandle, metafilename)
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/io/mcdparserbase.py", line 49, in __init__
    self.parse_mcd_xml()
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/io/mcdparserbase.py", line 160, in parse_mcd_xml
    self._meta = McdXmlParser(self.xml)
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/io/mcdxmlparser.py", line 244, in __init__
    meta = libb.dict_key_apply(meta, libb.strip_ns)
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/librarybase.py", line 47, in dict_key_apply
    iterable[new_key] = dict_key_apply(iterable[new_key], str_fkt)
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/librarybase.py", line 47, in dict_key_apply
    iterable[new_key] = dict_key_apply(iterable[new_key], str_fkt)
  File "/home/zhanxw/anaconda2/envs/imctools/lib/python3.8/site-packages/imctools/librarybase.py", line 43, in dict_key_apply
    for key in iterable.keys():
RuntimeError: dictionary keys changed during iteration

Can you help to fix this error? Thanks.

**Comment by votti** [comment]
I will look into it, thanks for reporting!

**Comment by votti** [comment]
So the issue was a change how dictionaries work in Python 3.8.
I have a fix in review but until this is on pip you can also just use an earlier Python version (e.g. 3.6) which should work.

**Comment by zhanxw** [comment]
Thank you. I will try 3.6.

**Comment by plankter** [comment]
There is a new release of imctools 1.0.5 that should fix this issue.

**Comment by zhanxw** [comment]
Python 3.6.7 worked. Thank you.
