### ISSUE TITLE
Unable to parse zipped mcd

### ISSUE THREAD

**Issue by jobha** [BodenmillerGroup/imctools#92]
* imctools version: 2.0.1
* Python version: 3.6.6
* Operating System: MacOS 10.15.6

### Description

I'm trying to run the IMC preprocessing pipeline. When trying to generate the analysis stack, I get the following error:

```
ERROR:root:Error in IMCAcquisition(11)_s1_p6_r4_a4_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
ERROR:root:Error in IMCAcquisition(11)_s1_p6_r4_a4_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
ERROR:root:Error in IMCAcquisition(11)_s1_p5_r2_a2_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
ERROR:root:Error in IMCAcquisition(11)_s1_p5_r2_a2_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
ERROR:root:Error in IMCAcquisition(11)_s1_p3_r1_a1_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
ERROR:root:Error in IMCAcquisition(11)_s1_p3_r1_a1_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
IMCAcquisition(11)_s1_p6_r4_a4_ac.ome.tiff
IMCAcquisition(11)_s1_p5_r2_a2_ac.ome.tiff
IMCAcquisition(11)_s1_p3_r1_a1_ac.ome.tiff
IMCAcquisition(11)_s1_p5_r3_a3_ac.ome.tiff
ERROR:root:Error in IMCAcquisition(11)_s1_p5_r3_a3_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
ERROR:root:Error in IMCAcquisition(11)_s1_p5_r3_a3_ac.ome.tiff
Traceback (most recent call last):
  File "<timed exec>", line 14, in <module>
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/scripts/ometiff2analysis.py", line 57, in ometiff_2_analysis
    writer = imc_img.get_image_writer(outname + ".tiff", metals=selmetals, mass=selmass)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisition.py", line 59, in get_image_writer
    order = self.get_metal_indices(metals)
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in get_metal_indices
    return [order_dict[m] for m in metallist]
  File "/Users/jobha/opt/anaconda3/envs/imctools/lib/python3.6/site-packages/imctools/io/imcacquisitionbase.py", line 106, in <listcomp>
    return [order_dict[m] for m in metallist]
KeyError: '166Er'
```

I have removed all entries in my pannel.csv file except this one, but I still get the error. I have checked that this tag is present in all my image files.

**Comment by votti** [comment]
Hi!
The issue is that the format needs to be "[Metal][Mass]" as this is how isotopes are stored file internally.
So you need to change the panel to 'Er166'.
Hope this helps!

**Comment by jobha** [comment]
That was my problem. Thank you.
